/**
 * read_yield_state.ts
 *
 * Reads the YieldPilot YieldState account from Solana using the Anchor client.
 * This script is useful for debugging and verifying on-chain state.
 */

import "dotenv/config";
import * as anchor from "@coral-xyz/anchor";
import { Connection, PublicKey } from "@solana/web3.js";

function mustGetEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`);
  }
  return value;
}

async function main() {
  // Load environment variables
  console.log("Program ID (raw):", JSON.stringify(process.env.YIELD_PILOT_PROGRAM_ID));
console.log("State Pubkey (raw):", JSON.stringify(process.env.YIELD_STATE_PUBKEY));
console.log("RPC Endpoint (raw):", JSON.stringify(process.env.SOLANA_RPC_ENDPOINT));
  const rpcEndpoint = mustGetEnv("SOLANA_RPC_ENDPOINT");
  const programId = new PublicKey(mustGetEnv("YIELD_PILOT_PROGRAM_ID"));
  const statePubkey = new PublicKey(mustGetEnv("YIELD_STATE_PUBKEY"));

  // Create Solana connection
  const connection = new Connection(rpcEndpoint, "confirmed");

  // Anchor wallet (loaded automatically from ANCHOR_WALLET env var)
  const wallet = anchor.Wallet.local();

  // Anchor provider
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  anchor.setProvider(provider);

  // Load the Anchor IDL generated by `anchor build`
  // Path may vary depending on your setup
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const idl = require("../target/idl/yield_pilot.json");

  // Create Anchor program client
  const program = new anchor.Program(idl, provider);

  // Get the proper account namespace key (IDL type may vary, use all lowercase snake_case)
  // Check program.account keys and use Object.keys(...) to debug if needed, but here is the likely fix:
  const state: any = await program.account['yieldState'].fetch(statePubkey);


  // Pretty-print the state
  console.log("YieldPilot YieldState:");
  console.log({
    authority: state.authority.toBase58(),
    currentProtocol: state.currentProtocol,
    currentApyBps: state.currentApyBps,
    currentApyPercent: (state.currentApyBps / 100).toFixed(2) + "%",
  });
}

main().catch((err) => {
  console.error("Failed to read YieldState:", err);
  process.exit(1);
});
